### ISSUE TITLE
`shouldHideErrorKey` for sub keys

### ISSUE THREAD

**Issue by bilgeyucel** [Hipo/hipo-exceptions-js#19]
I have an error as following:
```js
const errorInfo = {
      type: "ValidationError",
      detail: {
        manual_part_process_quotes: [
          {lead_time: ["Lead time is required."]},
          {lead_time: ["Lead time is required."]}
        ]
      },
      fallback_message: "Lead time is required."
    };
``` 

```js
const options = {
      shouldHideErrorKey: true,
      knownErrorKeys: ["name", "production_rate"]
    };
```

When I call `exceptionTransformer.generateErrorMessage(errorInfo, options)` function, it returns `lead_time: Lead time is required.`. IMO, it should return `Lead time is required` because of `shouldHideErrorKey: true`

**Comment by jamcry** [comment]
Thanks, you are right, for that case it should omit the key. I will look into the issue tomorrow
